spring:
  zipkin:    base-url: http://localhost:9411/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8001

eureka:
  instance: 
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging: 
  level: 
    root: info

endpoints: 
  sensitive: false
  beans: 
    sensitive: false

swagger: 
  groupName: ${spring.application.name}
  basePackage: com.flyonsky