spring:
  application:
    name: timeserver
  zipkin:    base-url: http://localhost:9411/

server:
  port: ${port}

eureka:
  instance: 
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/