spring:
  application:
    name: configserver  cloud:    config:      server:        git:          uri: https://github.com/flyonskycn/config.git
          search-paths:          - configserver
          username: flyonskycn
          password: 462017ufo

server:
  port: 7001

eureka:
  instance: 
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/