spring:
  application:
    name: configserver  cloud:    config:      server:        git:          uri: git@github.com:flyonskycn/config.git
          search-paths:          - configserver

server:
  port: 7001

eureka:
  instance: 
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/