spring:
  application:
    name: apigateway
  zipkin:
    base-url: http://localhost:9411/

server:  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:  ignored-services:  - timeserver

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream