spring:
  application:
    name: apigateway

server:  port: 8079

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:  ignored-services:  - timeserver
